In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.metrics import *
from pandas import DataFrame, Series

plt.style.use('seaborn')
sns.set(font_scale=2.5) 


In [2]:
stock_data = pd.read_csv('/Users/growing/Downloads/trade_train_set/stocks.csv')
trade_data = pd.read_csv('/Users/growing/Downloads/trade_train_set/trade_train.csv')

In [3]:
stock_data.shape, trade_data.shape

((286061, 15), (30200, 13))

In [4]:
columns=trade_data.columns
columns

Index(['Unnamed: 0', '기준년월', '그룹번호', '그룹내고객수', '종목번호', '그룹내_매수여부', '그룹내_매도여부',
       '매수고객수', '매도고객수', '평균매수수량', '평균매도수량', '매수가격_중앙값', '매도가격_중앙값'],
      dtype='object')

In [5]:
trade_data.head()

Unnamed: 0    기준년월   그룹번호  그룹내고객수     종목번호 그룹내_매수여부 그룹내_매도여부  매수고객수  매도고객수  \
0           0  201907  MAD01     288  A000660        Y        Y      7     17   
1           1  201907  MAD01     288  A001820        Y        Y      3      4   
2           2  201907  MAD01     288  A004020        Y        Y      3      3   
3           3  201907  MAD01     288  A005380        Y        Y      4      3   
4           4  201907  MAD01     288  A005930        Y        Y     13     19   

   평균매수수량  평균매도수량  매수가격_중앙값  매도가격_중앙값  
0      19     234     74800     78500  
1     533     154     47385     46700  
2     409     528     41411     40000  
3     323     451    140602    140628  
4      34     101     45350     46850

In [6]:
stock_data.head()

index      기준일자     종목번호       종목명 20년7월TOP3대상여부 시장구분 표준산업구분코드_대분류  \
0      0  20190701  A000020      동화약품             N  코스피          제조업   
1      1  20190701  A000080     하이트진로             N  코스피          제조업   
2      2  20190701  A000100      유한양행             Y  코스피          제조업   
3      3  20190701  A000120    CJ대한통운             N  코스피     운수 및 창고업   
4      4  20190701  A000140  하이트진로홀딩스             Y  코스피     금융 및 보험업   

       표준산업구분코드_중분류 표준산업구분코드_소분류    종목시가    종목고가    종목저가    종목종가     거래량  \
0  의료용 물질 및 의약품 제조업      의약품 제조업    9680    9840    9680    9710   31341   
1            음료 제조업    알코올음료 제조업   20550   20550   20200   20300  127186   
2  의료용 물질 및 의약품 제조업      의약품 제조업  259000  267500  250000  251500  395757   
3  육상운송 및 파이프라인 운송업    도로 화물 운송업  136500  137000  133000  136000   62513   
4               금융업       기타 금융업    9060    9190    8910    9000    7661   

   거래금액_만원단위  
0      30581  
1     258535  
2   10139357  
3     846100  
4       6896

In [7]:
trade_data.dtypes

Unnamed: 0     int64
기준년월           int64
그룹번호          object
그룹내고객수         int64
종목번호          object
그룹내_매수여부      object
그룹내_매도여부      object
매수고객수          int64
매도고객수          int64
평균매수수량         int64
평균매도수량         int64
매수가격_중앙값       int64
매도가격_중앙값       int64
dtype: object

In [8]:
stock_data['종목명'].value_counts() 

동화약품           268
메가엠디           268
인콘             268
호텔신라           268
선데이토즈          268
쇼박스            268
삼성엔지니어링        268
우원개발           268
시그네틱스          268
오션브릿지          268
아모레퍼시픽         268
유비쿼스홀딩스        268
액트로            268
대창             268
삼본전자           268
SKC솔믹스         268
풀무원            268
코웨이            268
칩스앤미디어         268
덱스터            268
뉴지랩            268
에이치엘비          268
넥스트BT          268
까스텔바작          268
헬릭스미스          268
이오테크닉스         268
포스코케미칼         268
엔브이에이치코리아      268
평화산업           268
노바렉스           268
              ... 
캐리소프트          187
티라유텍           185
아이티엠반도체        180
라파스            178
한화시스템          176
제테마            175
현대에너지솔루션       172
우양             171
코리아에셋투자증권      171
씨에스베어링         170
티움바이오          169
센트랄모텍          168
노터스            166
코리아센터          164
태웅로직스          157
제이엘케이          156
신테카바이오         152
메드팩토           150
브릿지바이오테라퓨틱스    149
메탈라이프          147
케이씨씨글라스        130
서남          

In [9]:
target_data_pool = stock_data.loc[stock_data['20년7월TOP3대상여부'].str.contains('Y', na = False)]
target_data_pool['종목명'].value_counts()

삼성전자우       268
포티스         268
CJ씨푸드       268
엔씨소프트       268
하나머티리얼즈     268
LG유플러스      268
KMH하이텍      268
한샘          268
아이에이네트웍스    268
이화공영        268
에코프로        268
한화솔루션       268
SK이노베이션     268
덕신하우징       268
태림포장        268
씨아이에스       268
큐리언트        268
모나미         268
농심          268
KB금융        268
이글벳         268
샘표식품        268
초록뱀         268
크루셜텍        268
디에이테크놀로지    268
다우기술        268
한미사이언스      268
삼성중공우       268
신라에스지       268
RFHIC       268
           ... 
상아프론테크      268
에이티넘인베스트    268
장원테크        268
KNN         268
삼성중공업       268
지노믹트리       268
한화우         268
삼성전자        268
이수페타시스      268
SK케미칼       268
롯데지주우       268
포스코인터내셔널    268
덱스터         268
케이씨텍        268
리드코프        268
인지디스플레      268
넥스트BT       268
중앙에너비스      268
셀트리온헬스케어    268
데일리블록체인     268
대화제약        268
슈프리마        268
젬백스         268
코윈테크        243
아톤          195
엔바이오니아      190
캐리소프트       187
한화시스템       176
메드팩토        150
이지바이오        38
Name: 종목명, Length: 135, 

In [10]:
target_data_pool = target_data_pool.drop_duplicates(subset = ['종목명'])

Answer  = target_data_pool['종목명'].values.tolist()
Answer

['유한양행',
 '하이트진로홀딩스',
 '중앙에너비스',
 'SK하이닉스',
 '한화우',
 'DB하이텍',
 'SK증권',
 '동양',
 '이화공영',
 '부광약품',
 '혜인',
 '대한항공',
 '현대제철',
 '농심',
 '롯데지주우',
 '모나미',
 '현대차',
 '삼성전자',
 '삼성전자우',
 '미래에셋대우',
 'GS리테일',
 '일양약품',
 '이수페타시스',
 '태평양물산',
 '대덕',
 '한미사이언스',
 '한샘',
 '한화솔루션',
 '삼성중공업',
 '삼성중공우',
 '웰바이오텍',
 'SOil',
 'CJ씨푸드',
 '태림포장',
 '유니크',
 '리드코프',
 '메디앙스',
 '한국전력',
 'SK텔레콤',
 '한온시스템',
 '신풍제약',
 '에이티넘인베스트',
 '코웨이',
 '롯데쇼핑',
 '다우기술',
 '대성엘텍',
 '신라에스지',
 '동아지질',
 'KT',
 '드래곤플라이',
 'LG유플러스',
 '비트컴퓨터',
 '시그네틱스',
 '체시스',
 'SK',
 'NAVER',
 '카카오',
 'SFA반도체',
 '엔씨소프트',
 '주성엔지니어링',
 '인지디스플레',
 '상상인',
 '두산인프라코어',
 '이글벳',
 '포스코인터내셔널',
 '유니온머티리얼',
 '초록뱀',
 '기가레인',
 '라이브플렉스',
 '큐로홀딩스',
 'LG화학',
 'SK바이오랜드',
 'KMH하이텍',
 '멕아이씨에스',
 'KNN',
 'KT서브마린',
 '넥스트BT',
 '와이오엠',
 '대화제약',
 '셀트리온',
 '젬백스',
 '에코프로',
 '케이씨티',
 '상아프론테크',
 '덕신하우징',
 '아모레퍼시픽',
 '셀트리온헬스케어',
 '테스',
 '씨젠',
 'SK이노베이션',
 '모베이스',
 '코오롱생명과학',
 'KB금융',
 '우진',
 '크루셜텍',
 '큐리언트',
 '아이에이네트웍스',
 '피앤이솔루션',
 '메가엠디',
 '데일리블록체인',
 'DGB금융지주',
 '포티스',
 '하나머티리얼즈',
 '장원테크'

In [11]:
stock_data['표준산업구분코드_대분류'].value_counts()

제조업                        185875
정보통신업                       37102
도매 및 소매업                    21172
금융 및 보험업                    14107
전문· 과학 및 기술 서비스업            10496
건설업                          5628
운수 및 창고업                     5517
수도· 하수 및 폐기물 처리· 원료 재생업      1608
서비스업                         1340
교육 서비스업                      1072
사업시설관리 및 사업지원 및 임대 서비스업       804
예술· 스포츠 및 여가관련                536
전기· 가스· 증기 및 공기조절 공급업         536
개인 서비스업                       268
Name: 표준산업구분코드_대분류, dtype: int64

In [12]:
group_trade = trade_data.groupby(trade_data['그룹번호'])

In [13]:
group_trade = trade_data.sort_values(by = ['그룹번호'], axis = 0)

In [14]:
group_trade['종목번호'].value_counts()

A005930    490
A000660    378
A068270    326
A035720    282
A051910    271
A005380    270
A009150    267
A006400    245
A215600    238
A005935    238
A091990    236
A028300    234
A066570    220
A207940    217
A035420    215
A015760    201
A008770    199
A008350    194
A096770    194
A006800    191
A010140    188
A078130    187
A032500    182
A005490    169
A096530    167
A090430    161
A034220    158
A005690    154
A003490    146
A105560    146
          ... 
A171090      1
A160550      1
A053590      1
A014190      1
A104040      1
A038060      1
A263770      1
A270870      1
A141020      1
A086980      1
A002780      1
A073540      1
A016920      1
A054620      1
A200670      1
A091340      1
A136540      1
A091580      1
A083450      1
A028100      1
A020180      1
A037460      1
A006890      1
A084870      1
A086670      1
A067990      1
A083500      1
A265560      1
A122350      1
A086890      1
Name: 종목번호, Length: 1066, dtype: int64

In [15]:
all_stock = trade_data.drop_duplicates(subset = ['종목번호'])

In [16]:
all_stock['종목번호'].value_counts()

A318010    1
A086390    1
A111710    1
A005180    1
A048430    1
A142760    1
A294630    1
A011040    1
A039130    1
A058110    1
A010600    1
A193250    1
A007370    1
A205100    1
A002140    1
A067390    1
A003280    1
A299660    1
A099440    1
A027360    1
A119860    1
A004140    1
A000210    1
A010620    1
A224060    1
A011150    1
A004020    1
A066970    1
A010060    1
A251270    1
          ..
A027740    1
A025870    1
A192080    1
A041590    1
A078890    1
A084990    1
A041920    1
A004710    1
A003410    1
A016920    1
A036180    1
A033180    1
A035900    1
A004990    1
A290510    1
A013810    1
A126640    1
A054780    1
A008560    1
A148150    1
A002790    1
A271560    1
A043220    1
A001200    1
A000150    1
A095340    1
A012450    1
A198440    1
A057880    1
A203690    1
Name: 종목번호, Length: 1066, dtype: int64

In [17]:
Y_class_sample = all_stock['종목번호'].values.tolist()

In [18]:
Y_class = np.array(Y_class_sample).reshape(-1,1)

In [19]:
Y_class

array([['A000660'],
       ['A001820'],
       ['A004020'],
       ...,
       ['A064240'],
       ['A086890'],
       ['A052860']], dtype='<U7')

In [20]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder() 
enc.fit(Y_class)

OneHotEncoder()

In [21]:
Y_class_encoding = enc.transform(Y_class).toarray()

In [22]:
Y_class_encoding

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
grouper = [g[1] for g in group_trade.groupby(['그룹번호'])]

In [25]:
for i in range(48):
    grouper[i] = grouper[i].sort_values(by = ['기준년월'], axis = 0)

In [26]:
grouper[0]

Unnamed: 0    기준년월   그룹번호  그룹내고객수     종목번호 그룹내_매수여부 그룹내_매도여부  매수고객수  \
0               0  201907  MAD01     288  A000660        Y        Y      7   
8               8  201907  MAD01     288  A009150        Y        Y     14   
7               7  201907  MAD01     288  A008770        Y        N      4   
6               6  201907  MAD01     288  A006400        Y        Y      6   
5               5  201907  MAD01     288  A005935        Y        Y      5   
4               4  201907  MAD01     288  A005930        Y        Y     13   
3               3  201907  MAD01     288  A005380        Y        Y      4   
2               2  201907  MAD01     288  A004020        Y        Y      3   
1               1  201907  MAD01     288  A001820        Y        Y      3   
11             11  201907  MAD01     288  A128940        Y        Y      3   
9               9  201907  MAD01     288  A034220        Y        Y      3   
10             10  201907  MAD01     288  A066570        Y        Y     15   
1538         1538  201908  MAD01     288  A005290        Y        Y      3   
1547         1547  201908  MAD01     288  A215600        Y        Y      4   
1546         1546  201908  MAD01     288  A138080        Y        Y      3   
1545         1545  201908  MAD01     288  A066570        Y        Y     12   
1537         1537  201908  MAD01     288  A000660        Y        Y     17   
1544         1544  201908  MAD01     288  A034220        Y        Y      4   
1543         1543  201908  MAD01     288  A020150        N        Y      0   
1542         1542  201908  MAD01     288  A009150        Y        Y     11   
1541         1541  201908  MAD01     288  A006400        Y        Y      7   
1539         1539  201908  MAD01     288  A005930        Y        Y     26   
1540         1540  201908  MAD01     288  A005935        Y        Y      8   
2979         2979  201909  MAD01     288  A068270        Y        Y      5   
2977         2977  201909  MAD01     288  A061970        Y        N      3   
2976         2976  201909  MAD01     288  A011070        Y        Y      3   
2975         2975  201909  MAD01     288  A009540        N        Y      0   
2974         2974  201909  MAD01     288  A009150        Y        Y      8   
2973         2973  201909  MAD01     288  A005935        Y        Y      3   
2978         2978  201909  MAD01     288  A066570        Y        Y      9   
...           ...     ...    ...     ...      ...      ...      ...    ...   
25296       25296  202006  MAD01     288  A009150        Y        Y     18   
25308       25308  202006  MAD01     288  A042660        Y        Y      3   
25309       25309  202006  MAD01     288  A051910        Y        Y      5   
25310       25310  202006  MAD01     288  A061970        Y        Y      3   
25311       25311  202006  MAD01     288  A065450        Y        Y      8   
25312       25312  202006  MAD01     288  A066570        Y        Y     28   
25304       25304  202006  MAD01     288  A034220        Y        Y      6   
25295       25295  202006  MAD01     288  A008770        Y        Y      5   
25292       25292  202006  MAD01     288  A005935        Y        Y     45   
25293       25293  202006  MAD01     288  A006400        Y        Y     31   
25285       25285  202006  MAD01     288  A000660        Y        Y     62   
25286       25286  202006  MAD01     288  A000990        Y        Y      4   
25287       25287  202006  MAD01     288  A001820        Y        Y      4   
25318       25318  202006  MAD01     288  A096770        Y        Y      6   
25319       25319  202006  MAD01     288  A105560        Y        Y      4   
25320       25320  202006  MAD01     288  A112610        Y        Y      4   
25321       25321  202006  MAD01     288  A207940        Y        Y      4   
25322       25322  202006  MAD01     288  A218410        Y        Y      4   
25294       25294  202006  MAD01     288  A006800        Y        Y      4   
25323       25323  202006  MA

In [27]:
stock_data.drop_duplicates(subset=['종목번호'])

index      기준일자     종목번호          종목명 20년7월TOP3대상여부 시장구분  \
0            0  20190701  A000020         동화약품             N  코스피   
1            1  20190701  A000080        하이트진로             N  코스피   
2            2  20190701  A000100         유한양행             Y  코스피   
3            3  20190701  A000120       CJ대한통운             N  코스피   
4            4  20190701  A000140     하이트진로홀딩스             Y  코스피   
5            5  20190701  A000145    하이트진로홀딩스우             N  코스피   
6            6  20190701  A000150           두산             N  코스피   
7            7  20190701  A000210         대림산업             N  코스피   
8            8  20190701  A000220         유유제약             N  코스피   
9            9  20190701  A000250        삼천당제약             N  코스닥   
10          10  20190701  A000270          기아차             N  코스피   
11          11  20190701  A000440       중앙에너비스             Y  코스닥   
12          12  20190701  A000520         삼일제약             N  코스피   
13          13  20190701  A000660       SK하이닉스             Y  코스피   
14          14  20190701  A000720         현대건설             N  코스피   
15          15  20190701  A000810         삼성화재             N  코스피   
16          16  20190701  A000880           한화             N  코스피   
17          17  20190701  A000885          한화우             Y  코스피   
18          18  20190701  A000890         보해양조             N  코스피   
19          19  20190701  A000910          유니온             N  코스피   
20          20  20190701  A000970        한국주철관             N  코스피   
21          21  20190701  A000990        DB하이텍             Y  코스피   
22          22  20190701  A001000         신라섬유             N  코스닥   
23          23  20190701  A001040           CJ             N  코스피   
24          24  20190701  A001060       JW중외제약             N  코스피   
25          25  20190701  A001120         LG상사             N  코스피   
26          26  20190701  A001140           국보             N  코스피   
27          27  20190701  A001200       유진투자증권             N  코스피   
28          28  20190701  A001210         금호전기             N  코스피   
29          29  20190701  A001230         동국제강             N  코스피   
...        ...       ...      ...          ...           ...  ...   
85274    85274  20191029  A317530        캐리소프트             Y  코스닥   
87397    87397  20191031  A322180         티라유텍             N  코스닥   
92275    92275  20191107  A084850      아이티엠반도체             N  코스닥   
94650    94650  20191111  A214260          라파스             N  코스닥   
96884    96884  20191113  A272210        한화시스템             Y  코스피   
97850    97850  20191114  A216080          제테마             N  코스닥   
101189  101189  20191119  A322000     현대에너지솔루션             N  코스피   
101924  101924  20191120  A103840           우양             N  코스닥   
102047  102047  20191120  A190650    코리아에셋투자증권             N  코스닥   
103293  103293  20191121  A297090       씨에스베어링             N  코스닥   
104389  104389  20191122  A321550        티움바이오             N  코스닥   
105443  105443  20191125  A308170        센트랄모텍             N  코스피   
107545  107545  20191127  A278650          노터스             N  코스닥   
109699  109699  20191129  A290510        코리아센터             N  코스닥   
116944  116944  20191210  A124560        태웅로직스             N  코스닥   
118311  118311  20191211  A322510        제이엘케이             N  코스닥   
122470  122470  20191217  A226330       신테카바이오             N  코스닥   
124631  124631  20191219  A235980         메드팩토             Y  코스닥   
125781  125781  20191220  A288330  브릿지바이오테라퓨틱스             N  코스닥   
127982  127982  20191224  A327260        메탈라이프             N  코스닥   
146298  146298  20200121  A344820      케이씨씨글라스             N  코스피   
167816  167816  20200220  A294630           서남             N  코스닥   
174290  174290  20200228  A294140           레몬             N  코스닥   
176426  176426  20200303  A274090   켄코아에어로스페이스             N  코스닥   
177372  177372  20200304  A204270        제이앤티씨             N  코스닥   
183938  183938  20200312  A237820         플레이디             N  코스닥   
186020 

In [28]:
pre_train_feature = [g[1] for g in grouper[0].groupby(['기준년월'])]

In [29]:
pre_train_feature[2]

Unnamed: 0    기준년월   그룹번호  그룹내고객수     종목번호 그룹내_매수여부 그룹내_매도여부  매수고객수  \
2979        2979  201909  MAD01     288  A068270        Y        Y      5   
2977        2977  201909  MAD01     288  A061970        Y        N      3   
2976        2976  201909  MAD01     288  A011070        Y        Y      3   
2975        2975  201909  MAD01     288  A009540        N        Y      0   
2974        2974  201909  MAD01     288  A009150        Y        Y      8   
2973        2973  201909  MAD01     288  A005935        Y        Y      3   
2978        2978  201909  MAD01     288  A066570        Y        Y      9   
2972        2972  201909  MAD01     288  A005930        Y        Y     16   
2971        2971  201909  MAD01     288  A000660        Y        Y     12   
2970        2970  201909  MAD01     288  A000270        Y        Y      5   

      매도고객수  평균매수수량  평균매도수량  매수가격_중앙값  매도가격_중앙값  
2979      4      18      46    168000    168500  
2977      0     682       0      8000        -1  
2976      3     283     251    106939    112166  
2975      3       0      30        -1    120500  
2974     10     166     569    100750     98914  
2973      5      10     262     39100     39050  
2978     10     159     258     65200     64500  
2972     34     129     273     46600     47600  
2971     11      57     123     79850     82300  
2970      3      72      21     44900     43850

In [30]:
pre_train_feature[11]

Unnamed: 0    기준년월   그룹번호  그룹내고객수     종목번호 그룹내_매수여부 그룹내_매도여부  매수고객수  \
25297       25297  202006  MAD01     288  A010140        Y        Y      7   
25298       25298  202006  MAD01     288  A011070        Y        Y      3   
25299       25299  202006  MAD01     288  A012330        Y        Y      5   
25315       25315  202006  MAD01     288  A086520        Y        Y      4   
25300       25300  202006  MAD01     288  A017960        Y        Y      3   
25302       25302  202006  MAD01     288  A020560        N        Y      0   
25303       25303  202006  MAD01     288  A032500        Y        Y      5   
25307       25307  202006  MAD01     288  A036460        Y        N      3   
25305       25305  202006  MAD01     288  A035420        Y        Y      5   
25306       25306  202006  MAD01     288  A035720        Y        Y      7   
25296       25296  202006  MAD01     288  A009150        Y        Y     18   
25308       25308  202006  MAD01     288  A042660        Y        Y      3   
25309       25309  202006  MAD01     288  A051910        Y        Y      5   
25310       25310  202006  MAD01     288  A061970        Y        Y      3   
25311       25311  202006  MAD01     288  A065450        Y        Y      8   
25312       25312  202006  MAD01     288  A066570        Y        Y     28   
25304       25304  202006  MAD01     288  A034220        Y        Y      6   
25295       25295  202006  MAD01     288  A008770        Y        Y      5   
25292       25292  202006  MAD01     288  A005935        Y        Y     45   
25293       25293  202006  MAD01     288  A006400        Y        Y     31   
25285       25285  202006  MAD01     288  A000660        Y        Y     62   
25286       25286  202006  MAD01     288  A000990        Y        Y      4   
25287       25287  202006  MAD01     288  A001820        Y        Y      4   
25318       25318  202006  MAD01     288  A096770        Y        Y      6   
25319       25319  202006  MAD01     288  A105560        Y        Y      4   
25320       25320  202006  MAD01     288  A112610        Y        Y      4   
25321       25321  202006  MAD01     288  A207940        Y        Y      4   
25322       25322  202006  MAD01     288  A218410        Y        Y      4   
25294       25294  202006  MAD01     288  A006800        Y        Y      4   
25323       25323  202006  MAD01     288  A253450        N        Y      0   
25317       25317  202006  MAD01     288  A091990        Y        Y      3   
25301       25301  202006  MAD01     288  A020150        Y        Y      7   
25316       25316  202006  MAD01     288  A090430        Y        Y      5   
25314       25314  202006  MAD01     288  A078600        Y        Y      3   
25288       25288  202006  MAD01     288  A003620        Y        Y      3   
25289       25289  202006  MAD01     288  A005380        Y        Y      9   
25290       25290  202006  MAD01     288  A005490        Y        Y      3   
25291       25291  202006  MAD01     288  A005930        Y        Y    105   
25324       25324  202006  MAD01     288  A336370        Y        Y      4   
25313       25313  202006  MAD01     288  A068270        Y        Y      5   

       매도고객수  평균매수수량  평균매도수량  매수가격_중앙값  매도가격_중앙값  
25297      9     492    4233      5869      6380  
25298      5      50     545    162291    158387  
25299      5      60      41    199833    196000  
25315      3     482     334     31550     31850  
25300      3     285     274      8537      8529  
25302      3       0      63        -1      4095  
25303      5      83     120     61100     60600  
25307      0      67       0     26600        -1  
25305      5       7       9    232200    245000  
25306      7      15      12    260500    256500  
25296     26     131     230    129500    132000  
25308      4      61      67     26227     26015  
25309     13      16      72    446000    456500  
25310      3    1256    1397      8592      9500  
25311      6     204     178     11000     

In [31]:
for i in range(12):
    pre_train_feature[i] = pre_train_feature[i].sort_values(by = ['매수고객수'], ascending = False)

In [32]:
pre_train_target_variable = []
for i in range(6):
    pre_train_target_variable.append(pre_train_feature[i+6].iloc[0]['종목번호']) 

In [33]:
pre_train_target_variable #가장 많이 매수한 종목..

['A005930', 'A005930', 'A005930', 'A005930', 'A005930', 'A005930']

In [34]:
print(Answer)

['유한양행', '하이트진로홀딩스', '중앙에너비스', 'SK하이닉스', '한화우', 'DB하이텍', 'SK증권', '동양', '이화공영', '부광약품', '혜인', '대한항공', '현대제철', '농심', '롯데지주우', '모나미', '현대차', '삼성전자', '삼성전자우', '미래에셋대우', 'GS리테일', '일양약품', '이수페타시스', '태평양물산', '대덕', '한미사이언스', '한샘', '한화솔루션', '삼성중공업', '삼성중공우', '웰바이오텍', 'SOil', 'CJ씨푸드', '태림포장', '유니크', '리드코프', '메디앙스', '한국전력', 'SK텔레콤', '한온시스템', '신풍제약', '에이티넘인베스트', '코웨이', '롯데쇼핑', '다우기술', '대성엘텍', '신라에스지', '동아지질', 'KT', '드래곤플라이', 'LG유플러스', '비트컴퓨터', '시그네틱스', '체시스', 'SK', 'NAVER', '카카오', 'SFA반도체', '엔씨소프트', '주성엔지니어링', '인지디스플레', '상상인', '두산인프라코어', '이글벳', '포스코인터내셔널', '유니온머티리얼', '초록뱀', '기가레인', '라이브플렉스', '큐로홀딩스', 'LG화학', 'SK바이오랜드', 'KMH하이텍', '멕아이씨에스', 'KNN', 'KT서브마린', '넥스트BT', '와이오엠', '대화제약', '셀트리온', '젬백스', '에코프로', '케이씨티', '상아프론테크', '덕신하우징', '아모레퍼시픽', '셀트리온헬스케어', '테스', '씨젠', 'SK이노베이션', '모베이스', '코오롱생명과학', 'KB금융', '우진', '크루셜텍', '큐리언트', '아이에이네트웍스', '피앤이솔루션', '메가엠디', '데일리블록체인', 'DGB금융지주', '포티스', '하나머티리얼즈', '장원테크', '와이제이엠게임즈', '퓨전', '디에이테크놀로지', '휴메딕스', '비씨월드제약', '덱스터', '로보로보', '강스템바이오텍', 'RFHIC', '씨아이에스', '케이엠제약', 

In [35]:
Answer_values = []
for i in range(len(Answer)):
    Answer_values.append(i)
Answer_len = len(Answer_values)
encoding = np.eye(Answer_len)[Answer_values]
print(encoding)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [37]:
target_data_pool

index      기준일자     종목번호       종목명 20년7월TOP3대상여부 시장구분  \
2            2  20190701  A000100      유한양행             Y  코스피   
4            4  20190701  A000140  하이트진로홀딩스             Y  코스피   
11          11  20190701  A000440    중앙에너비스             Y  코스닥   
13          13  20190701  A000660    SK하이닉스             Y  코스피   
17          17  20190701  A000885       한화우             Y  코스피   
21          21  20190701  A000990     DB하이텍             Y  코스피   
35          35  20190701  A001510      SK증권             Y  코스피   
36          36  20190701  A001520        동양             Y  코스피   
42          42  20190701  A001840      이화공영             Y  코스닥   
59          59  20190701  A003000      부광약품             Y  코스피   
60          60  20190701  A003010        혜인             Y  코스피   
68          68  20190701  A003490      대한항공             Y  코스피   
77          77  20190701  A004020      현대제철             Y  코스피   
84          84  20190701  A004370        농심             Y  코스피   
98          98  20190701  A00499K     롯데지주우             Y  코스피   
104        104  20190701  A005360       모나미             Y  코스피   
105        105  20190701  A005380       현대차             Y  코스피   
114        114  20190701  A005930      삼성전자             Y  코스피   
115        115  20190701  A005935     삼성전자우             Y  코스피   
129        129  20190701  A006800    미래에셋대우             Y  코스피   
134        134  20190701  A007070     GS리테일             Y  코스피   
141        141  20190701  A007570      일양약품             Y  코스피   
142        142  20190701  A007660    이수페타시스             Y  코스피   
146        146  20190701  A007980     태평양물산             Y  코스피   
147        147  20190701  A008060        대덕             Y  코스피   
157        157  20190701  A008930    한미사이언스             Y  코스피   
162        162  20190701  A009240        한샘             Y  코스피   
175        175  20190701  A009830     한화솔루션             Y  코스피   
180        180  20190701  A010140     삼성중공업             Y  코스피   
181        181  20190701  A010145     삼성중공우             Y  코스피   
...        ...       ...      ...       ...           ...  ...   
854        854  20190701  A195440        퓨전             Y  코스닥   
858        858  20190701  A196490  디에이테크놀로지             Y  코스닥   
862        862  20190701  A200670      휴메딕스             Y  코스닥   
864        864  20190701  A200780    비씨월드제약             Y  코스닥   
874        874  20190701  A206560       덱스터             Y  코스닥   
895        895  20190701  A215100      로보로보             Y  코스닥   
905        905  20190701  A217730   강스템바이오텍             Y  코스닥   
908        908  20190701  A218410     RFHIC             Y  코스닥   
915        915  20190701  A222080     씨아이에스             Y  코스닥   
922        922  20190701  A225430     케이엠제약             Y  코스닥   
928        928  20190701  A228760     지노믹트리             Y  코스닥   
932        932  20190701  A234100        세원             Y  코스닥   
933        933  20190701  A236200      슈프리마             Y  코스닥   
939        939  20190701  A239340      줌인터넷             Y  코스닥   
945        945  20190701  A242040      나무기술             Y  코스닥   
952        952  20190701  A248170      샘표식품             Y  코스피   
964        964  20190701  A257370    명성티엔에스             Y  코스닥   
972        972  20190701  A263720    디앤씨미디어             Y  코스닥   
994        994  20190701  A281820      케이씨텍             Y  코스피   
996        996  20190701  A285130     SK케미칼             Y  코스피   
999        999  20190701  A288620     에스퓨얼셀             Y  코스닥   
1003      1003  20190701  A290550      디케이티             Y  코스닥   
1021      1021  20190701  A307930     컴퍼니케이             Y  코스닥   
26752    26752  20190805  A282880      코윈테크             Y  코스닥   
76608    76608  20191017  A158430        아톤             Y  코스닥   
82105    82105  20191024  A317870    엔바이오니아             Y  코스닥   
85274    85274  20191029  A317530     캐리소프트             Y  코스닥   
96884    96884  20191113  A272210     한화시스템             Y  코스피   
124631  124631  20191219  A235980      메드팩토      

In [51]:
p = target_data_pool[target_data_pool['종목번호'] == pre_train_target_variable[0]]['종목명']


114    삼성전자
Name: 종목명, dtype: object

In [49]:
df = DataFrame(Answer)

In [53]:
encoding[17]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])